# Docker compose file for mysql version 8

version: '3.1'                      # specify docker-compose version
services:
  # The docker run command would be
  # docker run -d --name mysql_db \
  # -e MYSQL_ROOT_PASSWORD=root \
  # -e MYSQL_DATABASE=test \
  # -e MYSQL_USER=test \
  # -e #MYSQL_PASSWORD=test \
  # -p 3306:3306 \
  # -v $(pwd)/data:/var/lib/mysql \
  # mysql:8
  mysql_db:                         # Create a mysql_db container
    image: mysql:8.0.39                  # Use mysql version 8 image
    container_name: mysql_db        # Name of the container
    restart: always                 # Restart the container always
    environment:                    # Environment variables
      MYSQL_ROOT_PASSWORD: root     
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    ports:                          # Ports to expose
      - "3306:3306"
    volumes:                        # Volumes to mount
      - ./data/mysql:/var/lib/mysql
  mongo_db:
    image: mongo
    container_name: mongo_db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo:/data/db
  mongo_express:
    image: mongo-express
    container_name: mongo_express
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo_db:27017
    ports:
      - "8081:8081"
    depends_on:
      - mongo_db